[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://portfolio-pro-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
