services:
  - type: web
    name: portfolio-pro-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://saikrishnabalaka_db_user:Saikrishn%407@cluster0.uqyesid.mongodb.net/MY-API-PLAYGROUND?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: MY-API-PLAYGROUND-super-secret-jwt-key-2024-production
      - key: CLIENT_URL
        value: https://portfolio-pro-frontend.onrender.com
    healthCheckPath: /api/health
  
  - type: web
    name: portfolio-pro-frontend
    env: static
    plan: free
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://portfolio-pro-backend.onrender.com
